"""Age

Revision ID: 097cdf1636be
Revises: 9124593bb92b
Create Date: 2023-12-03 17:52:47.634665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097cdf1636be'
down_revision = '9124593bb92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
