"""added likes

Revision ID: 3f9e17b86401
Revises: edaee199dd3d
Create Date: 2024-05-12 17:58:49.134974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9e17b86401'
down_revision = 'edaee199dd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes2',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_downlike')
        batch_op.drop_index('ix_post_uplike')
        batch_op.drop_column('downlike')
        batch_op.drop_column('uplike')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uplike', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('downlike', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_post_uplike', ['uplike'], unique=False)
        batch_op.create_index('ix_post_downlike', ['downlike'], unique=False)

    op.drop_table('likes')
    # ### end Alembic commands ###
