"""comauthor

Revision ID: 4e69c03319de
Revises: ead70d045c7d
Create Date: 2024-02-28 19:29:52.297965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e69c03319de'
down_revision = 'ead70d045c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comauthor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_com_comauthor_id'), ['comauthor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_com_comauthor_id'))
        batch_op.drop_column('comauthor_id')

    # ### end Alembic commands ###
