"""Dislikes

Revision ID: 634f8b8f1ca8
Revises: 4e34f5458d34
Create Date: 2024-06-10 20:09:49.167264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634f8b8f1ca8'
down_revision = '4e34f5458d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dislikes')
    # ### end Alembic commands ###
