"""empty message

Revision ID: 6e0403a881f0
Revises: 4e69c03319de
Create Date: 2024-03-10 19:14:07.509754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0403a881f0'
down_revision = '4e69c03319de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashtags', sa.String(length=187), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_hashtags'), ['hashtags'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_hashtags'))
        batch_op.drop_column('hashtags')

    # ### end Alembic commands ###
