"""added com

Revision ID: ead70d045c7d
Revises: a82fb81943da
Create Date: 2024-02-25 17:41:25.940768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead70d045c7d'
down_revision = 'a82fb81943da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('com',
    sa.Column('comid', sa.Integer(), nullable=False),
    sa.Column('combody', sa.String(length=2000), nullable=True),
    sa.Column('comtimestamp', sa.DateTime(), nullable=True),
    sa.Column('compost_id', sa.Integer(), nullable=True),
    sa.Column('comimage', sa.Text(), nullable=True),
    sa.Column('comfileType', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['compost_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('comid')
    )
    with op.batch_alter_table('com', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_com_comtimestamp'), ['comtimestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_com_comtimestamp'))

    op.drop_table('com')
    # ### end Alembic commands ###
