"""empty message

Revision ID: edaee199dd3d
Revises: f58403dd1373
Create Date: 2024-04-14 20:18:44.179989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaee199dd3d'
down_revision = 'f58403dd1373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uplike', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('downlike', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_downlike'), ['downlike'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_uplike'), ['uplike'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_uplike'))
        batch_op.drop_index(batch_op.f('ix_post_downlike'))
        batch_op.drop_column('downlike')
        batch_op.drop_column('uplike')

    # ### end Alembic commands ###
