"""empty message

Revision ID: f58403dd1373
Revises: 6e0403a881f0
Create Date: 2024-03-13 19:25:16.631310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58403dd1373'
down_revision = '6e0403a881f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comuser', sa.String(length=25), nullable=True))
        batch_op.create_index(batch_op.f('ix_com_comuser'), ['comuser'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_com_comuser'))
        batch_op.drop_column('comuser')

    # ### end Alembic commands ###
